version: '3.3'

services:
  php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=aws-0-ap-southeast-1.pooler.supabase.com
      - DB_PORT=6543
      - DB_USER=postgres.qaerzlrgzbhcufkqqabt
      - DB_PASSWORD=123456Aa
      - DB_NAME=postgres