version: '3.3'

services:
  app:
    build: .
    container_name: php_app
    volumes:
      - ./laravel-learning-project:/src
    ports:
      - "9000:9000"
      - "8000:8000"  # laravel
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=aws-0-ap-southeast-1.pooler.supabase.com
      - DB_PORT=6543
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres.qaerzlrgzbhcufkqqabt
      - DB_PASSWORD=123456Aa
    working_dir: /src
    command: bash -c "composer install && php artisan key:generate --force && php artisan serve --host=0.0.0.0 --port=8000"